services:
  - type: web
    name: retrieval-qa-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false   # Set your OpenAI key in Render dashboard
      - key: SENTENCE_MODEL_NAME
        value: all-MiniLM-L6-v2
      - key: MAX_PDF_MB
        value: 20
      - key: MAX_PDF_PAGES
        value: 200
      - key: CHUNK_CHAR_TARGET
        value: 1200
      - key: CHUNK_CHAR_OVERLAP
        value: 180
      - key: TOP_K
        value: 3
      - key: REQUEST_TIMEOUT_SECONDS
        value: 60
      - key: ENABLE_CORS
        value: "true"
