services:
  - type: web
    name: hackrx-api
    env: python
    region: oregon
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: OPENROUTER_API_KEY
        value: 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
